package com.codevista.trace.model;

public enum TraceEventType {
    LINE,
    VARIABLE_DECLARATION,
    VARIABLE_ASSIGNMENT,
    CONDITION_EVALUATION,
    LOOP_ITERATION,
    LOOP_TERMINATION,
    METHOD_ENTRY,
    METHOD_EXIT,
    ARRAY_ACCESS,
    ARRAY_MUTATION,
    OBJECT_CREATION,
    FIELD_MUTATION,
    COLLECTION_OPERATION,
    EXCEPTION_THROWN,
    EXCEPTION_CAUGHT,
    THREAD_STATE,
    OUTPUT_PRINT
}
